export const assets = {
  icons: {
    nine: "/icons/9.svg",
    apple: "/icons/apple.svg",
    arrow: "/icons/arrow.svg",
    chart: "/icons/chart.svg",
    circle: "/icons/circle.svg",
    dollar: "/icons/doller.svg",
    earth: "/icons/earth.svg",
    emoji: "/icons/emoji.svg",
    facebook: "/icons/fb.svg",
    flower: "/icons/flower.svg",
    googlePlay: "/icons/gplay.svg",
    graph: "/icons/graph.svg",
    instagram: "/icons/insta.svg",
    linkedin: "/icons/linkdin.svg",
    message: "/icons/msg.svg",
    refresh: "/icons/refresh.svg",
    star: "/icons/star 1.svg",
    upperArrow: "/icons/upper-arrow.svg",
    walletAdd: "/icons/wallet-add.svg",
    wallet: "/icons/wallet.svg",
    wing: "/icons/wing.svg",
    x: "/icons/x.svg",
    youtube: "/icons/yt.svg",
  },
  images: {
    avatarOne: "/images/dp-1.png",
    avatarTwo: "/images/dp-2.png",
    hexagon: "/images/hexagon.svg",
    mobile: "/images/mobile.png",
    mobileTwo: "/images/mobile-2.png",
    mobileThree: "/images/mobile-3.png",
    pieChart: "/images/pichart.svg",
    vectorCurve: "/images/vector-curve.svg",
    visa: "/images/visa.png",
  },
} as const;
