export const assets = {
  icons: {
    velocity: "/icons/velocity.svg",
    apple: "/icons/apple.svg",
    arrow: "/icons/arrow.svg",
    goldlines: "/icons/goldlines.svg",
    satisfaction: "/icons/satisfaction.svg",
    dollar: "/icons/doller.svg",
    waves: "/icons/waves.svg",
    emoji: "/icons/emoji.svg",
    facebook: "/icons/fb.svg",
    travelers: "/icons/travelers.svg",
    googlePlay: "/icons/gplay.svg",
    chart: "/icons/chart.svg",
    instagram: "/icons/insta.svg",
    linkedin: "/icons/linkdin.svg",
    message: "/icons/msg.svg",
    refresh: "/icons/refresh.svg",
    star: "/icons/star 1.svg",
    upperArrow: "/icons/upper-arrow.svg",
    walletAdd: "/icons/wallet-add.svg",
    wallet: "/icons/wallet.svg",
    wing: "/icons/wing.svg",
    x: "/icons/x.svg",
    rotashow: "/icons/rotashow.svg",
    arrowDown: "/icons/arrow-down.svg",
  },
  images: {
    avatarOne: "/images/dp-1.png",
    avatarTwo: "/images/dp-2.png",
    hexagon: "/images/hexagon.svg",
    mobile: "/images/mobile.png",
    mobileTwo: "/images/mobile-2.png",
    mobileThree: "/images/mobile-3.svg",
    pieChart: "/images/pichart.svg",
    vectorCurve: "/images/vector-curve.svg",
    visa: "/images/visa.png",
  },
} as const;
